# Generated by Django 3.2.4 on 2021-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstatelyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
