# Generated by Django 3.2.4 on 2021-11-25 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstatelyApp', '0003_auto_20211102_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bookmarks',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
